build:
    environment:
        php: 5.6
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
