language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer --dev install

script:
  - vendor/bin/phpunit --coverage-text

notifications:
  email:
    - franjid@gmail.com

